version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "double trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally