version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: rm -rf node_modules
      - run: rm -f package-lock.json
      - run: npm install
      - run: CI=false npm run build
  test:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install react-scripts
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: echo "helllooooo !"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere